### ISSUE TITLE
make it build

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-libp2p#1]
doesn't build yet. working on it.

HSUISHFDIUHDFIUFHDIFHFIOHFIOSJFIOIFDJSOIDFJSIODO golang packages

**Comment by diasdavid** [comment]
<3 :)

**Comment by tilgovi** [comment]
:dolphin:

**Comment by jbenet** [comment]
@whyrusleeping did you push your extraction here? does it build?

**Comment by whyrusleeping** [comment]
it builds when you pull down the extra deps. I havent finished the vendoring yet as i'm taking it slowly to build out proper tooling. As it stands, any go code that isnt already vendored with godeps can be easily turned into a gx package with `gx-go import --rewrite <package import path>`. The `gx` tooling itself is now very pleasant to use, and i'm *almost* to the point where we can do the global install stuff we discussed.  (took a look at how godeps strips out the canonical import paths)

**Comment by whyrusleeping** [comment]
it builds!

**Comment by jbenet** [comment]
Yaaaaay!! :D
