### ISSUE TITLE
Set of examples

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-libp2p#19]
It would be really helpful, if can get an folder with the following examples:

- [ ] Start two libp2p Nodes (create and make them listen)
- [ ] Set up a handler for a protocol (through multistream)
- [ ] Dial from one Node to the other, when both Nodes have TCP and uTP set up + SPDY (Yamux can be there too)
- [ ] Dial from one Node to the other having set up secio too

**Comment by diasdavid** [comment]
Hey @whyrusleeping 

I made an example with the JS version: 

https://github.com/ipfs/js-libp2p-ipfs/blob/master/examples/example.js

It is really simple, as all of the work happens underneath. Can we have something similar in Go as well?

**Comment by whyrusleeping** [comment]
Done!

**Comment by noffle** [comment]
Where are these?

**Comment by whyrusleeping** [comment]
Oh, it might make sense to post a link here...

https://github.com/whyrusleeping/libp2p-examples

**Comment by noffle** [comment]
Awesome! Let's make them discoverable now: could we either a) add these to this repo, or b) link to your examples repo in this repo's readme?
