### ISSUE TITLE
missed deps

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-libp2p#3]
- github.com/satori/go.uuid
- github.com/whyrusleeping/go-logging
- github.com/jbenet/go-datastore
- p2p/host/basic/basic_host_test.go:12:2: cannot find package "command/vendor/QmacZi9WygGK7Me8mH53pypyscHzU386aUZXpr28GZgUct/context" in any of:
        /usr/local/go/src/command/vendor/QmacZi9WygGK7Me8mH53pypyscHzU386aUZXpr28GZgUct/context (from $GOROOT)
- p2p/peer/peer_test.go:14:2: cannot find package "command-line-/vendor/QmNsoHoCVhgXcv1Yg45jtkMgimxorTAN36fV9AQMFXHHAQ/go-base58" in any of:
        /usr/local/go/src/command-line-/vendor/QmNsoHoCVhgXcv1Yg45jtkMgimxorTAN36fV9AQMFXHHAQ/go-base58 (from $GOROOT)
- p2p/peer/addr_manager_test.go:7:2: cannot find package "command-line-/vendor/QmbWxL1aXQhBjc1XGjGF1f2KGBMCBYSuT2ThA8YXnXJK83/go-multiaddr" in any of:
        /usr/local/go/src/command-line-/vendor/QmbWxL1aXQhBjc1XGjGF1f2KGBMCBYSuT2ThA8YXnXJK83/go-multiaddr (from $GOROOT)
- p2p/metrics/stream/metered_test.go:8:2: cannot find package "com/vendor/QmciEePSP8wpGYZp8fsPFi49Ya7xQMUFwFj2z5fDpfZnhC/randbo" in any of:
        /usr/local/go/src/com/vendor/QmciEePSP8wpGYZp8fsPFi49Ya7xQMUFwFj2z5fDpfZnhC/randbo (from $GOROOT)
- p2p/net/mock/mock_test.go:17:2: cannot find package "command-l/vendor/QmacZi9WygGK7Me8mH53pypyscHzU386aUZXpr28GZgUct/context" in any of:
        /usr/local/go/src/command-l/vendor/QmacZi9WygGK7Me8mH53pypyscHzU386aUZXpr28GZgUct/context (from $GOROOT)

@whyrusleeping

**Comment by whyrusleeping** [comment]
github.com/jbenet/go-msgio
github.com/jbenet/go-reuseport

**Comment by whyrusleeping** [comment]
github.com/whyrusleeping/go-metrics

**Comment by whyrusleeping** [comment]
github.com/coreos/go-semver/semver
github.com/fd/go-nat

**Comment by whyrusleeping** [comment]
github.com/jbenet/go-detect-race

**Comment by whyrusleeping** [comment]
this is all fixed now! :D
