### ISSUE TITLE
go-ipfs cleanup

### ISSUE THREAD

**Issue by rht** [ipfs/go-libp2p#9]
Either:
1. components of go-ipfs are to be yanked out of it (e.g. gateway, ipfswatch, seccat)
2. go-ipfs as a collection of such tools + UX stuff, it is the libp2p parts that are to be yanked out

Which one is preferable?
Ref: https://github.com/ipfs/go-ipfs/pull/2006

**Comment by whyrusleeping** [comment]
i would say both, yank those programs all out into their separate repos. go-libp2p is already extracted, and just waiting on gx decisions before we pull all of p2p out to be replaced by this repo
